// let friends = ['Mike','John','Lisa','Jane'];
// console.log(friends.length);
// console.log(friends[2]);
// friends[2] = 'Jack';
// console.log(friends);
// let mixer = ['Hello',50,true,100,600,null,[1,2,3]];
// console.log(mixer);
// mixer[6][1] = 100;
// console.log(mixer);
// console.log(mixer.toString());
// let mixer2 = mixer.toString();
// let joiner = friends.join('----*----');
// console.log(joiner);

let friends = ['Mike', 'John', 'Lisa', 'Jane'];
console.log(friends.length);
console.log(friends[2]);
friends[2] = 'Jack';
console.log(friends);
let mixer = ['Hello', 50, true, 100, 600, null, [1, 2, 3]];
console.log(mixer.length);
console.log(mixer[6]);
console.log(mixer[6][1]);
mixer[6][1] = 100;
console.log(mixer);
console.log(mixer.toString());
let mixer2 = mixer.toString();
console.log(mixer2[2]);
let joiner = friends.join();
console.log(joiner);
let joiner2 = friends.join('---*---');
console.log(joiner2);