// let okay = true;
// let notOkay = false;
// console.log(typeof okay);
// console.log(typeof notOkay);
// let message = ['Hello', 'JavaScript'];
// let checker = message.includes('JavaScript');
// console.log(checker);
// let message2 = 'Hello JavaScript';
// console.log(message2.includes('JavaScript'));
// console.log(message == 'JavaScript');
// console.log(message == 'Hello JavaScript');
// console.log(5 == 5);
// console.log(5 != 5);
// console.log(10 < 5);
// console.log(1 <= 5);
// console.log(1 >= 5);
console.log('5' == 5);
console.log('5' === 5); //'5' === 5 Three equal sign check if data types are same
console.log('5' !== 5);
console.log(typeof ('5'));
console.log(typeof (5));
console.log(typeof (true));